# Generated by Django 4.1.1 on 2022-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=10000000)),
                ('image', models.ImageField(upload_to='blogs')),
                ('draft', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
